
INC	:= -I$(CUDA_HOME)/include -I.
LIB	:= -L$(CUDA_HOME)/lib64 -lcudart -lm


NVCCFLAGS	:= -O -arch=sm_30 -lineinfo -maxrregcount 63 --ptxas-options=-v --use_fast_math
# NVCCFLAGS	:= -g -G -arch=sm_30 --ptxas-options=-v --use_fast_math

all:		BS_3D_timing

BS_3D_timing:	BS_3D_timing.cu Makefile utilities.h trid.h
	nvcc BS_3D_timing.cu -o BS_3D_timing $(INC) $(NVCCFLAGS) $(LIB)

clean:
	rm -f BS_3D_timing


